{
  description = "Omarchy - Base configuration flake";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # Pinned to the v0.56.x release branch, NOT main. main migrated the config
    # format from hyprlang `.conf` to Lua: it ignores hyprland.conf outright and
    # writes an autogenerated hyprland.lua in its place, silently discarding this
    # flake's entire home-manager config, and it dropped `hyprctl keyword` (IPC is
    # Lua now), which modules/home-manager/lid/hyprland.nix is built on. v0.56.2 is not an
    # ancestor of main -- it branches at 36b2e0c -- so the release line stays on
    # `.conf`. v0.56.0 rather than v0.56.2 because .2 took only half of 91f29f2:
    # the nixpkgs bump past glaze 8 without the CMakeLists change relaxing
    # `find_package(glaze 7...<8)`, leaving it unable to configure under Nix.
    #
    # aquamarine is overridden forward past c0bd9ed ("drm: do not stash failed
    # commits", Jul 20) -- the SIGSEGV in SDRMConnector::releaseStashedCommit that
    # killed the session on every third-monitor hotplug. aaed248 is the last rev
    # before the Jul 27 bump to 0.14.0, so it stays on VERSION 0.13.0 / soname
    # .so.12 and keeps ABI compatibility with what v0.56.0 was built against.
    # Overriding only .url preserves the follows v0.56.0 declares on aquamarine's
    # own nixpkgs/systems/hyprutils/hyprwayland-scanner inputs.
    hyprland = {
      url = "github:hyprwm/Hyprland/v0.56.0";
      inputs.aquamarine.url = "github:hyprwm/aquamarine/aaed2488ebcb555b53938bf5cf4abca9d8611e1d";
    };
    nix-colors.url = "github:misterio77/nix-colors";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # GTK4 settings app for Hyprland. Not in nixpkgs yet (NixOS/nixpkgs#505419);
    # drop this input and use pkgs.hyprmod once that lands.
    hyprmod = {
      url = "github:BlueManCZ/hyprmod";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    elephant.url = "github:abenz1267/elephant";

    walker = {
      url = "github:abenz1267/walker";
      inputs.elephant.follows = "elephant";
    };
  };
  outputs =
    inputs@{
      self,
      nixpkgs,
      hyprland,
      nix-colors,
      home-manager,
      ...
    }:
    {
      formatter.x86_64-linux = nixpkgs.legacyPackages.x86_64-linux.nixfmt-tree;

      devShells.x86_64-linux.default = import ./shells/qt.nix {
        pkgs = nixpkgs.legacyPackages.x86_64-linux;
      };

      nixosModules = {
        default =
          {
            lib,
            ...
          }:
          {
            imports = [
              (import ./modules/nixos/t2-dsp.nix)
              (import ./modules/nixos/default.nix inputs)
            ];

            options.omarchy = (import ./config.nix lib).omarchyOptions;
            config = {
              nixpkgs.config.allowUnfree = true;
            };
          };
      };

      homeManagerModules = {
        default =
          {
            lib,
            osConfig ? { },
            ...
          }:
          {
            imports = [
              inputs.walker.homeManagerModules.default
              nix-colors.homeManagerModules.default
              (import ./modules/home-manager/default.nix inputs)
            ];
            options.omarchy = (import ./config.nix lib).omarchyOptions;
            config = lib.mkIf (osConfig ? omarchy) {
              omarchy = osConfig.omarchy;
            };
          };
      };
    };
}
